contact:
  email: "roja.rahmani@mmk.su.se"
  linkedin: "https://www.linkedin.com/in/rojarahmani/?originalSubdomain=se"
  google_scholar: "https://scholar.google.com/citations?user=d_L7oNgAAAAJ&hl=en"
  description: "I’m always open to scientific collaboration, particularly in the areas of molecular modeling, free energy calculations, and biomolecule-nanomaterial interactions. If you are working on experimental studies and looking for computational support to complement your research, feel free to reach out."
